"use client";
import {useEffect,useState} from "react";
import {Activity,BookOpen,Bot,BrainCircuit,CalendarDays,CheckCircle2,ChevronRight,Clock3,GitBranch,Layers3,ListTodo,Mic,Plus,Search,Sparkles,Target,X} from "lucide-react";
type Decision={id:number,title:string,context:string,rationale:string,impact:string,status:string,createdAt:string};
const seed:Decision[]=[
 {id:1,title:"Codex será o executor principal",context:"Evitar uma estrutura de agentes permanentes que aumente custo e coordenação.",rationale:"Um responsável preserva contexto. Subagentes serão temporários e usados apenas quando o trabalho puder ser dividido.",impact:"O relógio comanda; o Nexus organiza; o Codex executa.",status:"Ativa",createdAt:"2026-09-29T13:42:00"},
 {id:2,title:"Nuvem por padrão, computador sob demanda",context:"O relógio precisa iniciar trabalhos mesmo com o computador desligado.",rationale:"Software roda hospedado e retorna pelo GitHub; o PC fica reservado para USB e hardware.",impact:"Execução contínua sem bloquear a máquina pessoal.",status:"Ativa",createdAt:"2026-09-29T14:05:00"},
 {id:3,title:"QBIT será a presença do Nexus",context:"O relógio precisa parecer vivo sem imitar um smartwatch comum.",rationale:"Manter o personagem original reduz esforço e cria vínculo imediato.",impact:"QBIT representa espera, trabalho, dúvida, sucesso e alerta.",status:"Ativa",createdAt:"2026-09-29T12:18:00"}
];
const nav=[{n:"Hoje",i:Target},{n:"Projetos",i:Layers3},{n:"Trabalho",i:ListTodo},{n:"Decisões",i:BrainCircuit},{n:"Método",i:BookOpen},{n:"Agenda",i:CalendarDays}];
const jobs=[{name:"Arquitetura do painel Nexus",state:"Em andamento",p:68},{name:"Mapear integração Codex Cloud",state:"Aguardando revisão",p:100},{name:"Portar animações do QBIT",state:"Planejado",p:12}];
export default function Home(){const[tab,setTab]=useState("Hoje"),[decisions,setDecisions]=useState(seed),[open,setOpen]=useState(false),[q,setQ]=useState(""),[form,setForm]=useState({title:"",context:"",rationale:"",impact:""});useEffect(()=>{fetch("/api/decisions").then(r=>r.json()).then(d=>d.decisions?.length&&setDecisions(d.decisions)).catch(()=>{})},[]);async function save(e:React.FormEvent){e.preventDefault();const temp={id:Date.now(),...form,status:"Ativa",createdAt:new Date().toISOString()};setDecisions(x=>[temp,...x]);setOpen(false);setForm({title:"",context:"",rationale:"",impact:""});const r=await fetch("/api/decisions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}).catch(()=>null);if(r?.ok){const d=await r.json();setDecisions(x=>x.map(v=>v.id===temp.id?d.decision:v))}}
return <main className="shell"><aside><div className="brand"><div className="eyes"><i/><i/></div><div><b>NEXUS</b><small>personal intelligence</small></div></div><nav>{nav.map(({n,i:I})=><button className={tab===n?"on":""} onClick={()=>setTab(n)} key={n}><I size={18}/>{n}{n==="Trabalho"&&<em>3</em>}</button>)}</nav><div className="systems"><label>SISTEMAS</label><p><i/>Codex Cloud<small>1 tarefa ativa</small></p><p><i className="off"/>QBIT<small>não conectado</small></p><p><i/>Memória<small>sincronizada</small></p></div><footer><span>K</span><div><b>Kozie</b><small>Administrador</small></div></footer></aside><section className="workspace"><header><div>Nexus <ChevronRight size={13}/> <b>{tab}</b></div><button><Search size={16}/> Buscar no Nexus <kbd>⌘ K</kbd></button><span><i/> sincronizado</span></header><div className="content">{tab==="Hoje"&&<Today go={setTab} add={()=>setOpen(true)}/>} {tab==="Decisões"&&<Decisions data={decisions.filter(d=>(d.title+d.context+d.rationale).toLowerCase().includes(q.toLowerCase()))} q={q} setQ={setQ} add={()=>setOpen(true)}/>} {tab==="Método"&&<Method/>}{tab==="Trabalho"&&<Work/>}{tab==="Projetos"&&<Projects/>}{tab==="Agenda"&&<Agenda/>}</div></section><button className="qbit"><span className="eyes"><i/><i/></span><div><b>QBIT</b><small>Pronto para ouvir</small></div><Mic size={18}/></button>{open&&<div className="shade"><form className="modal" onSubmit={save}><div className="modal-head"><div><small>NOVA MEMÓRIA</small><h2>Registrar decisão</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div>{[["title","O que foi decidido?"],["context","Qual situação levou à decisão?"],["rationale","Por que este caminho fez sentido?"],["impact","O que muda a partir daqui?"]].map(([k,p])=><label key={k}>{k==="title"?"Título":k==="context"?"Contexto":k==="rationale"?"Por quê":"Impacto"}<textarea required={k==="title"} value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={p}/></label>)}<div className="actions"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">Guardar na memória</button></div></form></div>}</main>}
function Head({eyebrow,title,text,add}:{eyebrow:string,title:string,text:string,add?:()=>void}){return <div className="head"><div><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div>{add&&<button className="primary" onClick={add}><Plus size={17}/> Registrar decisão</button>}</div>}
function Today({go,add}:{go:(s:string)=>void,add:()=>void}){return <><Head eyebrow="TERÇA-FEIRA · 29 SET" title="Boa tarde, Kozie." text="Uma frente está em movimento e três decisões já formam o método Nexus." add={add}/><div className="focus"><Sparkles/><div><small>FOCO ATUAL</small><b>Transformar o Nexus em uma memória operacional que pensa junto com você.</b></div><button onClick={()=>go("Método")}>Ver método <ChevronRight/></button></div><div className="metrics"><Metric i={ListTodo} n="Em execução" v="1" d="Arquitetura do painel"/><Metric i={Clock3} n="Aguardando você" v="2" d="Revisões pendentes"/><Metric i={BrainCircuit} n="Decisões" v="3" d="2 adicionadas hoje"/><Metric i={CalendarDays} n="Próximo bloco" v="15:00" d="Desenvolvimento"/></div><div className="columns"><section className="panel"><Title t="Trabalho em movimento" a="Ver fila" go={()=>go("Trabalho")}/>{jobs.map(j=><div className="job" key={j.name}><Bot/><div><b>{j.name}</b><small>Nexus · {j.state}</small><span><i style={{width:j.p+"%"}}/></span></div><em>{j.p}%</em></div>)}</section><section className="panel"><Title t="Linha do tempo" a="Abrir memória" go={()=>go("Decisões")}/><Timeline time="14:12" title="Painel Nexus iniciado"/><Timeline time="13:42" title="Codex definido como executor"/><Timeline time="12:18" title="QBIT definido como presença"/></section></div><section className="panel principles"><Title t="Princípios ativos" a="Explorar método" go={()=>go("Método")}/><div><Principle n="01" t="Registrar antes de esquecer"/><Principle n="02" t="Uma voz, execução distribuída"/><Principle n="03" t="Reversível por padrão"/></div></section></>}
function Decisions({data,q,setQ,add}:{data:Decision[],q:string,setQ:(s:string)=>void,add:()=>void}){return <><Head eyebrow="MEMÓRIA DECISÓRIA" title="Decisões" text="Não guarde apenas o que foi escolhido. Preserve por que aquilo fez sentido." add={add}/><div className="filter"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar contexto, motivo ou impacto"/><span>{data.length} registros</span></div><div className="decision-list">{data.map(d=><article key={d.id}><div>D-{String(d.id).slice(-3)}</div><section><header><h2>{d.title}</h2><span>{d.status}</span></header><p>{d.context}</p><dl><div><dt>POR QUÊ</dt><dd>{d.rationale}</dd></div><div><dt>IMPACTO</dt><dd>{d.impact}</dd></div></dl><footer><Clock3/> {new Date(d.createdAt).toLocaleString("pt-BR")}</footer></section></article>)}</div></>}
const ps=["Registrar antes de esquecer","Uma voz, execução distribuída","Reversível por padrão"];
function Method(){return <><Head eyebrow="SISTEMA DE PENSAMENTO" title="Método Nexus" text="Princípios extraídos das suas próprias decisões: um sistema vivo, não um manual estático."/><div className="method"><BrainCircuit/><div><small>VERSÃO 0.1</small><h2>Pensar com memória. Agir com clareza.</h2><p>Decisões viram padrões; padrões viram princípios; princípios orientam a próxima ação.</p></div></div><div className="principle-list">{ps.map((p,i)=><article key={p}><span>0{i+1}</span><div><h2>{p}</h2><p>{i===0?"Toda escolha importante guarda contexto, razão e consequência.":i===1?"Você fala com o Nexus; o Codex coordena a execução.":"Mudanças começam isoladas, são verificadas e só então entram no fluxo."}</p></div><CheckCircle2/></article>)}</div></>}
function Work(){return <><Head eyebrow="CODEX CLOUD" title="Trabalho" text="Uma fila clara do que está sendo executado, revisado ou planejado."/><div className="kanban">{jobs.map(j=><article key={j.name}><span><Bot/> Nexus</span><h2>{j.name}</h2><p>{j.state}</p><div className="bar"><i style={{width:j.p+"%"}}/></div><footer><GitBranch/> codex/{j.name.toLowerCase().replaceAll(" ","-").slice(0,20)}</footer></article>)}</div></>}
function Projects(){return <><Head eyebrow="MAPA DE TRABALHO" title="Projetos" text="Cada frente reúne contexto, decisões, arquivos e sessões do Codex."/><div className="projects">{[["NX","Nexus","Cérebro pessoal, painel e orquestração.",42],["TW","T-Watch","QBIT, firmware e interface do relógio.",18],["OP","Operações","Agenda, trabalhos e rotinas conectadas.",8]].map(x=><article key={x[0]}><b>{x[0]}</b><small>ATIVO</small><h2>{x[1]}</h2><p>{x[2]}</p><div className="bar"><i style={{width:x[3]+"%"}}/></div><footer>{x[3]}% estruturado <ChevronRight/></footer></article>)}</div></>}
function Agenda(){return <><Head eyebrow="TEMPO E INTENÇÃO" title="Agenda" text="Compromissos e blocos de foco reunidos com o trabalho que depende deles."/><div className="agenda"><div><span>SET</span><b>29</b><small>terça-feira</small></div><section><Event time="15:00" title="Desenvolvimento do Nexus"/><Event time="18:30" title="Revisar trabalho do Codex"/></section></div></>}
function Metric({i:I,n,v,d}:{i:any,n:string,v:string,d:string}){return <article><I/><small>{n}</small><b>{v}</b><p>{d}</p></article>}function Title({t,a,go}:{t:string,a:string,go:()=>void}){return <header className="title"><h2>{t}</h2><button onClick={go}>{a}<ChevronRight/></button></header>}function Timeline({time,title}:{time:string,title:string}){return <div className="timeline"><time>{time}</time><i/><div><b>{title}</b><p>Registrado na memória operacional.</p></div></div>}function Principle({n,t}:{n:string,t:string}){return <article><span>{n}</span><b>{t}</b><p>Contexto, consequência e aprendizado conectados.</p></article>}function Event({time,title}:{time:string,title:string}){return <div><time>{time}</time><article><small>FOCO</small><h2>{title}</h2><p>Contexto conectado ao projeto Nexus.</p></article></div>}
