"use client";
import {useEffect,useMemo,useState} from "react";
import {addDoc,getDocs,query,where} from "firebase/firestore";
import {auth} from "../lib/firebase";
import {nexusStore} from "../lib/nexus-store";
import {knowledge} from "../lib/knowledge";
import {coreTopics,inferredTopics,noteTopics,type Topic} from "../lib/topics";

export function TopicSystem({compact=false}:{compact?:boolean}){
 const[personal,setPersonal]=useState<Topic[]>([]),[selected,setSelected]=useState("nexus"),[name,setName]=useState(""),[description,setDescription]=useState(""),[error,setError]=useState("");
 useEffect(()=>{const user=auth?.currentUser;if(!user)return;let active=true;getDocs(query(nexusStore.topics(),where("ownerId","==",user.uid))).then(result=>{if(active)setPersonal(result.docs.map(item=>{const data=item.data();return{id:item.id,name:String(data.name??""),description:String(data.description??""),origin:"Koziel" as const,keywords:Array.isArray(data.keywords)?data.keywords.map(String):[]}}))}).catch(()=>{if(active)setError("Não foi possível carregar seus temas.")});return()=>{active=false}},[]);
 const topics=[...coreTopics,...personal,...inferredTopics];
 const current=topics.find(item=>item.id===selected)??topics[0];
 const related=useMemo(()=>knowledge.filter(note=>{const explicit=noteTopics[note.id]?.includes(current.id);const body=`${note.title} ${note.summary} ${note.detail}`.toLocaleLowerCase("pt-BR");return explicit||current.keywords.some(word=>body.includes(word.toLocaleLowerCase("pt-BR")))}),[current]);
 async function createTopic(e:React.FormEvent){e.preventDefault();const user=auth?.currentUser;if(!user)return;const clean=name.trim();if(!clean)return;if(topics.some(item=>item.name.toLocaleLowerCase("pt-BR")===clean.toLocaleLowerCase("pt-BR"))){setError("Esse tema já existe.");return}try{const record={name:clean.toLocaleUpperCase("pt-BR"),description:description.trim(),keywords:[clean.toLocaleLowerCase("pt-BR")],ownerId:user.uid,origin:"Koziel"};const result=await addDoc(nexusStore.topics(),record);setPersonal(items=>[...items,{id:result.id,name:record.name,description:record.description,keywords:record.keywords,origin:"Koziel"}]);setSelected(result.id);setName("");setDescription("");setError("")}catch{setError("Não foi possível guardar o tema.")}}
 return <section className={`topics-panel ${compact?"topics-compact":""}`}><div className="topics-heading"><div><small>ORGANIZAÇÃO DO CÉREBRO</small><h2>Temas que dão sentido às memórias</h2></div><span>{topics.length} temas · {inferredTopics.length} propostos pela IA</span></div><div className="topics-columns"><div className="topic-groups"><label>DEFINIDOS POR KOZIEL</label><div className="topic-buttons">{[...coreTopics,...personal].map(item=><button key={item.id} className={selected===item.id?"active":""} onClick={()=>setSelected(item.id)}>{item.name}</button>)}</div><label>IDENTIFICADOS PELO NEXUS</label><div className="topic-buttons ai">{inferredTopics.map(item=><button key={item.id} className={selected===item.id?"active":""} onClick={()=>setSelected(item.id)}>{item.name}</button>)}</div></div><article className="topic-detail"><small>{current.origin==="Koziel"?"TEMA DEFINIDO POR VOCÊ":"TEMA PROPOSTO PELA IA"}</small><h3>{current.name}</h3><p>{current.description}</p><div className="topic-memories"><b>{related.length} {related.length===1?"memória relacionada":"memórias relacionadas"}</b>{related.length?related.map(note=><span key={note.id}>{note.title}<small>{note.kind}</small></span>):<em>Área reservada. Ainda não há arquivos ou decisões confiáveis sobre este tema.</em>}</div></article></div>{!compact&&<form className="new-topic" onSubmit={createTopic}><div><b>Adicionar um tema seu</b><small>Fica guardado na sua base privada.</small></div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do tema" required/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="O que pertence a ele?"/><button type="submit">Criar tema</button></form>}{error&&<p className="topic-error">{error}</p>}</section>
}
