export type KnowledgeNote = {id:string; title:string; kind:"visao"|"decisao"|"arquitetura"|"projeto"|"pendencia"; summary:string; detail:string; links:string[]; source:string};

// Curadoria verificável do histórico desta conversa e dos arquivos do projeto.
// Fontes externas (como exportações do Claude) só entram após leitura, nunca por suposição.
export const knowledge:KnowledgeNote[] = [
  {id:"nexus",title:"Nexus",kind:"visao",summary:"Cérebro operacional pessoal",detail:"Reunir trabalhos, agenda, decisões, contexto e histórico num painel que permita pensar e agir com continuidade.",links:["watch","qbit","codex","memory","firebase","agenda"],source:"Conversa atual · criação do Nexus"},
  {id:"watch",title:"Relógio mandante",kind:"visao",summary:"A interface de comando do sistema",detail:"O relógio deve ser a forma rápida de conversar com o Nexus, pedir informações e iniciar serviços, sem ser o executor pesado.",links:["nexus","qbit","codex","hardware"],source:"Conversa atual · papel do relógio"},
  {id:"qbit",title:"QBIT",kind:"decisao",summary:"Presença visual e voz do Nexus",detail:"Usar o QBIT já existente; preservar o olhinho, sem redesenhar um personagem novo. O relógio deve parecer uma tecnologia própria, não um smartwatch genérico.",links:["watch","nexus","hardware"],source:"Conversa atual · escolha do mascote"},
  {id:"codex",title:"Codex executor",kind:"decisao",summary:"Execução principal do trabalho",detail:"O Nexus organiza e despacha; o Codex realiza o trabalho. Outros agentes só entram quando um serviço específico justificar essa divisão, evitando uma equipe permanente desnecessária.",links:["nexus","watch","cloud"],source:"Conversa atual · orquestração"},
  {id:"cloud",title:"Nuvem por padrão",kind:"decisao",summary:"PC reservado ao trabalho local",detail:"O serviço deve continuar disponível quando o computador pessoal estiver desligado. O PC permanece útil para USB, firmware e testes físicos; GitHub guarda e sincroniza código, mas sozinho não executa o cérebro.",links:["codex","firebase","hardware"],source:"Conversa atual · hospedagem e computador"},
  {id:"memory",title:"Memória de decisões",kind:"decisao",summary:"Guardar contexto, motivo e consequência",detail:"O banco precisa ser um cérebro de longo prazo: registrar o que foi decidido, por que, de onde veio, que projetos afeta e quando deve ser revisado. Inspirado na experiência de notas conectadas do Obsidian.",links:["nexus","method","firebase","projects"],source:"Conversa atual · nível Obsidian"},
  {id:"method",title:"Método Nexus",kind:"visao",summary:"Transformar escolhas em modo de pensar",detail:"Capturar informação, conectá-la a projetos e decisões, revisá-la e extrair princípios úteis. Uma decisão não deve aparecer como fato sem sua origem e sua justificativa.",links:["memory","nexus"],source:"Conversa atual · método de pensar"},
  {id:"firebase",title:"Base Firebase nexus",kind:"arquitetura",summary:"Dados separados do ERP",detail:"Projeto Firebase erp-galpas, banco nomeado nexus. Login Google e regras de acesso limitadas ao e-mail autorizado. Há coleções preparadas, mas a experiência de notas ainda está em evolução.",links:["nexus","memory","cloud"],source:"nexus-panel/lib/nexus-store.ts; firestore.nexus.rules"},
  {id:"hardware",title:"T-Watch Ultra",kind:"projeto",summary:"ESP32-S3 + rádio SX1262",detail:"Hardware do relógio confirmado como LILYGO T-Watch Ultra. O rádio LoRa precisa de região/frequência definida antes de transmissão; desenvolvimento local inclui gravação e testes físicos.",links:["watch","qbit","cloud"],source:"docs/lilygo.md; docs/arquitetura.md; conversa atual"},
  {id:"projects",title:"Projetos conectados",kind:"visao",summary:"Trabalhos, tarefas e decisões num lugar",detail:"Cada trabalho deve manter contexto, arquivos, tarefas, decisões relacionadas e histórico de execução. O painel Nexus é o ponto de encontro, não um substituto automático de todas as ferramentas.",links:["nexus","memory","agenda","codex"],source:"Conversa atual · escopo do painel"},
  {id:"agenda",title:"Agenda contextual",kind:"visao",summary:"Compromissos ligados ao trabalho",detail:"A agenda deve informar prioridades e ações do Nexus. Integração real ainda não foi conectada; horários de demonstração não são compromissos confirmados.",links:["nexus","projects","watch"],source:"Conversa atual · agenda; estado do painel"},
  {id:"voice",title:"Conversa ao vivo",kind:"pendencia",summary:"Interação por voz com o QBIT",detail:"Objetivo futuro: conversar naturalmente com o personagem no relógio, receber informação e iniciar trabalho. Depende de áudio, conectividade, serviço seguro e testes de latência.",links:["watch","qbit","nexus"],source:"Conversa atual · conversa em tempo real"},
];

export const researchReferences = [
  {name:"Khoj",url:"https://github.com/khoj-ai/khoj",lesson:"Busca e respostas apoiadas em documentos com fonte; útil para a camada de recuperação."},
  {name:"Opensidian",url:"https://github.com/markusbegerow/opensidian",lesson:"Wikilinks, backlinks e grafo interativo; útil para navegação entre notas."},
  {name:"personal-brain",url:"https://github.com/alvinekelund/personal-brain",lesson:"Nós com tipos, relações e trilha de origem; útil para não confundir inferência com fato."},
];
